### ISSUE TITLE
Deploy G2P PoC to AWS and integrate with complete solution

### ISSUE THREAD

**Issue by vijayg10** [sp-convergence/mojaloop-g2p-poc-demo#1]
## **Goal**:
`As a` stakeholder

`I want to` deploy G2P PoC to an AWS EC2 instance
  
`so that` I can integrate the payment execution system to other components like MOSIP and openCRVS for an end to end demo

**Acceptance Criteria**:

- [ ] G2P Poc is deployed in AWS
- [ ] AWS Deployment instructions are available in the repository
- [ ] The solution is aligned with the other components like MOSIP and openCRVS
- [ ] End to End demo is recorded / presented

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Dockerfiles are created for various components in the demo
- [ ] Docker-compose script is created with proper configuration to run the demo easily
- [ ] Deploy the demo in AWS EC2 instance
- [ ] Document the deployment instructions
- [ ] Work with other team members for integrating the solution with MOSIP and openCRVS
- [ ] End to End demo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Documentation is updated

## **Pull Requests**:
- NA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: TBC
